docker-build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t accelingvo .
    - docker run -p 8150:8150 accelingvo
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
